cmake_minimum_required(VERSION 3.8)
project(turtle_cpp)
if(NOT CMAKE_CXX_STANDARD) set(CMAKE_CXX_STANDARD 17) endif()
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_msgs REQUIRED)
find_package(turtlesim REQUIRED)
add_executable(distance_publisher_cpp src/distance_publisher.cpp)
add_executable(distance_monitor_cpp src/distance_monitor.cpp)
ament_target_dependencies(distance_publisher_cpp rclcpp std_msgs turtlesim)
ament_target_dependencies(distance_monitor_cpp rclcpp std_msgs)
install(TARGETS distance_publisher_cpp distance_monitor_cpp DESTINATION lib/${PROJECT_NAME})
ament_package()
