<?xml version="1.0"?>
<package format="3">
  <name>turtle_py</name><version>0.1.0</version><description>Module 2 Python ROS2 nodes</description>
  <maintainer email="student@example.com">HyeoungJungKwon</maintainer><license>Apache-2.0</license>
  <depend>rclpy</depend><depend>std_msgs</depend><depend>geometry_msgs</depend><depend>turtlesim</depend><depend>std_srvs</depend><depend>tf2_ros</depend><depend>tf_transformations</depend><depend>visualization_msgs</depend><depend>turtle_interfaces</depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <test_depend>ament_pytest</test_depend><test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
